
---
Resources:
  CFTVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.40.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: workspaces-bravo-01
        - Key: Created
          Value: 2021-06-22-1328
  VPCSN01:  
    Type: AWS::EC2::Subnet
    Properties: 
      VpcId: !Ref CFTVPC
      AvailabilityZone: !Select [ 0, !GetAZs ]
      CidrBlock: 10.40.11.0/24
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name
          Value: "wkspbravo-west-public-1st"
      