
---
Resources:
  CFTVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.40.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: workspaces-bravo-01
        - Key: Created
          Value: 2021-06-22-1328
