Resources:
  mySecretMSFTad:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: MSFTadSecretAdmin
      Description: "Test Secret 20211208-0644-16"
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 30
      Tags: 
        - Key: Created
          Value: "20211208-0644-16"
        - Key: ResourceTarget
          Value: "Microsoft Active Directory Admin Credentials"
          
 